### ISSUE TITLE
here is some usage examples

### ISSUE THREAD

**Issue by sloev** [cocrawler/cdx_toolkit#10]
# a general iterator script that takes a url_prefix with asterisk and outputs to an html directory

[gist](https://gist.github.com/sloev/db4c45c8e3ac4aee4bb267eb5fcfbb97)

usage:
> python fetch.py 'https://open.spotify.com/*'

# a spotify scraper using common crawl as datasource

[gist](https://gist.github.com/sloev/6e528f07f82b3a8af5bd7b8450ebf0b5)

usage:
> python download_spotify.py >> data.json

**Comment by wumpus** [comment]
I will do #12 based on this.

**Comment by sloev** [comment]
@wumpus thanx for a great repo!
