### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by sergicloud** [cocrawler/cdx_toolkit#11]
how can I query just domain names? (without /path/to/files ) and unspecified all tld (no *.com *.io..). I would like to get a just unique domains dataset

**Comment by wumpus** [comment]
You can directly download a list of all of the domains from Common Crawl.

https://commoncrawl.org/2020/06/host-and-domain-level-web-graphs-febmarmay-2020/

There is a valid cdx query that can return this, but the transformations that the CDX server makes to the url you send in makes it difficult to make it. And it would be very inefficient.

**Comment by sergicloud** [comment]
Thank you, but the data is only 2020? I would like to get it all.

**Comment by sergicloud** [comment]
It seems it's limited to 2017-2020, and I will have to parse it by hand. Mind to share the query or snippet to get CDX query?
Thanks
> There is a valid cdx query that can return this, but the transformations that the CDX server makes to the url you send in makes it difficult to make it. And it would be very inefficient.

**Comment by wumpus** [comment]
btw this query is trivial in the columnar index.

**Comment by sergicloud** [comment]
What do you mean? I have never used CDX and I found your useful library (just modify the query for * .tld) but I would have to go through each tld and then delete the paths, and surely there is some more optimal and faster way.

**Comment by sergicloud** [comment]
> btw this query is trivial in the columnar index.

What do you mean? I have never used CDX and I found your useful library (just modify the query for * .tld) but I would have to go through each tld and then delete the paths, and surely there is some more optimal and faster way.

**Comment by sergicloud** [comment]
I don't want to bother you, so I apologize for asking again, but I have a personal university project a bit stuck because of an small domains dataset (it has to be free and open sources to be reproducible) and if you are so kind to help me I thank you,
