### ISSUE TITLE
next(CDXFetcherIter) hangs when cc request returns 400/404

### ISSUE THREAD

**Issue by windymay** [cocrawler/cdx_toolkit#16]
OS: Windows 10
Python 3.8.5
cdx_toolkit 0.9.29
requests 2.24.0

So recently iterations on CDXFetcherIter hang on some urls, below is an example:
```python
url = 'http://www.illinoishomepage.net/news/local-news/man-who-fell-through-ice-dies'
cdx = cdx_toolkit.CDXFetcher(source='cc')
next(cdx.iter(url, from_ts='201301',to='201709'))
```
And it turns out that on my machine, this request always returns 404:
```python
cc_url = 'https://index.commoncrawl.org/CC-MAIN-2017-34-index'
params = {'to': '20170930235959', 'url': 'http://www.illinoishomepage.net/news/local-news/man-who-fell-through-ice-dies', 'output': 'json', 'page': 0, 'from': '20130101000000'}
headers = {'User-Agent': 'pypi_cdx_toolkit/installed-from-git'}
resp = requests.get(cc_url, params=params, headers=headers,
                                timeout=(30., 30.), allow_redirects=False)
```
And because of the way 404 is handled, `CDXFetcherIter.get_more()` will run this request over and over again with increasing page but `self.captures` remains `[]`, causing the loop to hang. 

I don't know if it's a temporary common crawl server error or it's related to my local connection. but same error last for 3 days now. So I think adding an option to limit number of pages or number of retries of `get_more()` would be nice. Thank you!

**Comment by windymay** [comment]
I did not use cdx server api before so I don't know its behavior before but it seems that with a large page number, the request would eventually return 400, for example with page=0 
https://index.commoncrawl.org/CC-MAIN-2020-50-index?url=http%3A%2F%2Fwww.illinoishomepage.net%2Fnews%2Flocal-news%2Fman-who-fell-through-ice-dies&output=json&page=0
return 404, text is "error no capture".   
But with page=1, 
https://index.commoncrawl.org/CC-MAIN-2020-50-index?url=http%3A%2F%2Fwww.illinoishomepage.net%2Fnews%2Flocal-news%2Fman-who-fell-through-ice-dies&output=json&page=1
 returns 400 and `get_more()` will move to next endpoint.

But for my example above, for CC-MAIN-2017-34-index, no matter what the page number is, for example, page=1000000, https://index.commoncrawl.org/CC-MAIN-2017-34-index?url=http%3A%2F%2Fwww.illinoishomepage.net%2Fnews%2Flocal-news%2Fman-who-fell-through-ice-dies&output=json&page=1000000
 still returns 404 with text "error no capture". And `get_more()` will keep increasing the page number and retry.

**Comment by wumpus** [comment]
Sebastian fixed this bug on the Common Crawl side, it was a missing index file for just that one index. It happened because the index moved to a new server recently. Thanks for finding it!

I will add some kind of guard to the code, so this infinite loop is at least a visible infinite loop.
