### ISSUE TITLE
Results not complete for Common Crawl index 2012

### ISSUE THREAD

**Issue by yujianll** [cocrawler/cdx_toolkit#20]
This is related to the comment in issue #17.
The following code returns nothing:
```
cdx = cdx_toolkit.CDXFetcher(source='cc')
url = "www.cnn.com/*"
objs = cdx.iter(url, from_ts='201207', to='201212', filter=['status:200', 'mime:text/html'])
```
I also ran this code `objs = cdx.iter(url, from_ts='201201', to='201206', filter=['status:200', 'mime:text/html'])` and it returns some results. However, the results only contain data before 201207. So it seems the data between 201207 - 201212 are missing?
Similarly, `objs = cdx.iter(url, from_ts='201301', to='201306', filter=['status:200', 'mime:text/html'])` only returns data after 201304.

**Comment by wumpus** [comment]
The crawling was not continuous.
