### ISSUE TITLE
`collinfo.json` URL returning empty list

### ISSUE THREAD

**Issue by nfmcclure** [cocrawler/cdx_toolkit#24]
Hi, thanks for this package and the work you have done.

I'm running: 

```
import cdx_toolkit

cdx = cdx_toolkit.CDXFetcher(source='cc')
```

And getting:

`
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File ".../venv/lib/python3.8/site-packages/cdx_toolkit/__init__.py", line 215, in __init__
    self.raw_index_list = get_cc_endpoints(self.cc_mirror)
  File ".../venv/lib/python3.8/site-packages/cdx_toolkit/commoncrawl.py", line 25, in get_cc_endpoints
    raise ValueError('Surprisingly few endpoints for common crawl index')  # pragma: no cover
ValueError: Surprisingly few endpoints for common crawl index
`

I did some looking, and it appears the code is checking:

[https://index.commoncrawl.org/collinfo.json](https://index.commoncrawl.org/collinfo.json)

For indices.  No matter how I open or query that link, all I get is an empty list.  I'm willing to work around this or work on a patch- but I can't seem to find an alternative to `collinfo.json` or where a list of indices are kept.

**Comment by wumpus** [comment]
Common Crawl's bucket is having an outage. When it is over, collinfo.json will return to normal.

**Comment by wumpus** [comment]
Things appear to have returned to normal.
