### ISSUE TITLE
Command-line tools are shipped with non-portable Python runtime

### ISSUE THREAD

**Issue by sebastian-nagel** [cocrawler/cdx_toolkit#4]
The command-line tools (cdx_iter and cdx_size) when installed via pip contain a non-portable Python runtime: 
```
#!/home/lindahl/.pyenv/versions/3.6.4/bin/python
```
The non-portable runtime is already deployed in the [wheel file (0.9.20)](https://files.pythonhosted.org/packages/26/ea/22c88c8fcd9244cf3fe635d9d641035cd94acde6ef5c97ffcae30467e0ba/cdx_toolkit-0.9.20-py3-none-any.whl) and is not to replaced when the package is installed via `pip3 install cdx_toolkit` on Linux (Ubuntu 18.04).

**Comment by wumpus** [comment]
Hm. It's not in the source, the source has #!/usr/bin/env python ... I'll have to see if I can figure out who's doing it.

**Comment by wumpus** [comment]
A quick look at setackoverflow shows that everyone else has the same cargo cult issues that I do with setuptools (cough, cough), and that switching from bdist_wheel to sdist avoids the problem. I don't have anything that needs a bdist, so that's a fine fix.

**Comment by sebastian-nagel** [comment]
Thanks! 0.9.21 is installed without this issue.
