### ISSUE TITLE
WET-files

### ISSUE THREAD

**Issue by Cenzor** [cocrawler/cdx_toolkit#6]
Thank you for your cdx_toolkit! This is great toolkit!
I have one question.
Can I get wet-files from commoncrawl.org using the cdx_toolkit? Or convert warc-file to wet-file?

Thank's

**Comment by wumpus** [comment]
Sadly, no, there is no CDX index for Common Crawl's WET files. Last I asked Sebastian, he was considering adding WET and WAT to the columnar index, but I don't think that's happened yet.

The tools that Common Crawl uses to convert warc to wet are available from Common Crawl.

These questions are better asked on the Common Crawl mailing list, which has archives of people also asking these questions, they're popular ones.
