### ISSUE TITLE
Is it possible to get only one URL of one domain from a TLD?

### ISSUE THREAD

**Issue by Chris8080** [cocrawler/cdx_toolkit#7]
Hello,

I'm trying to look at some specifics only at certain URLs of domains.

Currently, I'm doing:
```
    url = '*.co.uk/'
    cdx = cdx_toolkit.CDXFetcher(source='cc')
    objs = list(cdx.iter(url, from_ts='202006', to='202006',
                     limit=1000, filter='=status:200'))
```
and it finds and the 1000 URLs and iterates over them (might be few dozen domains).
Is there a filter I can employ, if I am only interested in the front page for instance?

Thanks,
Chris

**Comment by wumpus** [comment]
You didn't show what the value of `url` is, that's an easy way to get just the front page: don't use `url = "commoncrawl.org/*"`, leave off the final `"*"`.

**Comment by Chris8080** [comment]
True .. I've forgot that one.
I'd like to get all all front pages from one specific TLD.

It seems as if:
url = '*.co.uk/' and url = '*.co.uk/*' and url = '*.co.uk' are just doing the same and get all URLs from one domain in the index.

Conceptually speaking:
cdx = cdx_toolkit.CDXFetcher(source='cc')
is retreiving the index
and the iter method will still send one request per URL to Amazon?
In this case, I could iterate through my URLs without using the index and just retrieve the HTML from the crawl files and it would cause the same amount of requests?
(I was looking to reduce the amount of requests, if that's anyhow possible)

**Comment by wumpus** [comment]
Unfortunately that's a hard-to-explain aspect of the cdx index. "*.co.uk" is actually a query for the surt "^co.uk.". You could add an additional regex filter on the url, but then you're descending into the swamp of details of exactly how surts are computed... does "pbm.com/" turn into "com.pbm)" or "com.pbm)/"? Only experimentation will tell you.

**Comment by Chris8080** [comment]
Ok, I see. I'll try around there and check the results. 
Thank you.
